services:
  - type: web
    name: scrible-outliner
    runtime: static
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/outliner/browser
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
